### ISSUE TITLE
Remove pre-populated text from filter label input field

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#123]
Think this was added by accident but we should remove the pre-populated "Search" text in "Text" and "Dropdown" filter label input fields.

![image](https://user-images.githubusercontent.com/24258161/51159805-dddcdb80-18ef-11e9-9559-74e9b81e0603.png)

**Comment by robbieaverill** [comment]
It may have been a midunderstanding of the designs rather than an accident:

![image](https://user-images.githubusercontent.com/5170590/51169559-7f423e00-18ac-11e9-8a21-fbadcd9963aa.png)

In this case it might simplify our "auto generate the label" discussion to just use the label you type in instead.

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-ckan-registry/pull/124
