### ISSUE TITLE
Discussion: Decide how we're going to approach front-end implementation

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-ckan-registry#62]
Currently our plans for `1.0` involve providing a simple table that displays the data of a chosen resource from CKAN. The columns of this table are configurable by the content author through the admin interface, and filters are provided to search/filter the results in the table.

The tricky part of this is that all our data and filtering is done through the CKAN API with GET requests. The ideal scenario is that we remove the SilverStripe site from fetching this data so that would mean building the table with JavaScript. This falls into line with what was discussed briefly during research: https://trello.com/c/t3ABKo8j/41-options-for-frontend-results .

The concern with this is that we're removing too much "template-ability" from the developer.

@NightJar @robbieaverill @unclecheese and myself have discussed this quite a bit. This is what we've discussed:

### Do it the React way: 
 - The developer who finds value in a React implementation is probably the same developer who will be happy making their own React mini-app
 - We'll want some easy way to allow components to be substituted or to have HOCs applied (Injector?)
 - We're not sure if we can leverage JS Injector on the front-end although the assumption is "probably"
 - We will have to be careful with architecture / separation of concerns to ensure that the developer is not limited (and would therefore have to recreate the whole app)
 - There's a POC available that would probably reduce the amount of work to do
 - It's possible that our React code will conflict with the sites own React code - what happens when some React 16 code runs on the same page as some React 10 code (for example)?
 - Potentially sets a new trend? SilverStripe supported modules providing React code for front-end sites?

### Do it the SSViewer way:
 - The SilverStripe site will have to act as a sort of proxy for data.govt.nz - it'll do the requests rather than the client side (JS)
 - It'll be slower & use SSP/CWP resources as well as the same amount of resource on data.govt
 - It will be super familiar for developers to template their own tables (or result sets)
 - Even if we go this route we should ensure that everything is exposed via `Content-Type: application/json` for an eventual React front-end to consume. This is still catering for ReactJS apps.

The last time we spoke we were considering the SSViewer way would probably be the way to go. Now I'm not sure again - but there's probably some bullet points under the React section that should be understood before we jump into it.

Perhaps @chillu and @camfindlay have an opinion here? This is something we'll be working on early in the new year, sorry for the short notice over the Christmas / New year break 🙇 .

**Comment by robbieaverill** [comment]
My opinion is "Do it the SSViewer way"

**Comment by chillu** [comment]
I'm strongly in favour of making this a use case of a decoupled architecture, where not every data exchange needs to be funnelled through a monolithic stack like the CMS. Yes, there's a bit more of a learning curve for SilverStripe developers, but at the same time it's lower for every non-SilverStripe developer.

I think the discussion about injectable React components is a bit of a red herring. This is required in the CMS because it's too complex of an architecture to allow devs to customise by assembling their own app behaviours based on provided React components (and Redux actions etc). And because we can't (yet) require `npm build` for basic CMS customisations. See [No need for DI in React](https://medium.com/@maxheiber/no-need-for-dependency-injection-in-react-components-641182760aaa).

My recommendation would be that you document how to *customise the style* of the output for developers. If modification of the actual frontend behaviour is required, developers should create their own view layer. This could be as simple as copy-pasting the `<App>` component we'd create, and exchanging bits in there as required. This is how virtually all React view layers work, our injectable CMS is the exception rather than the rule.  Compare this to e.g. the [Griddle customisation](http://griddlegriddle.github.io/Griddle/docs/customization/) architecture. 

Which incidentally is what I would recommend you look into as a base (Griddle), since this is mostly about customising a table, right? I'd imagine that there's a `<FilterProvider>` and a `<ColumnProvider>` which take our specific data definitions set in the CMS and generate.

Overall, I think philosophically our approach needs to shift a bit to providing strong guarantees on the data definition layer (GraphQL), and good defaults on the view layer (themes, components). But the expectation is that either you're OK with those defaults (plus a few superficial tweaks), *or* you're happy developing your own view layer without us getting in your way. This middle ground of creating super customiseable views is very build and maintenance intensive (since we're creating a lot of API surface), and a lot of overhead to learn. That's why pattern libraries and the component approach became so popular in frontend development in my opinion: Clear separation of concerns between what's a "library" (generic), and how this library is assembled for a use case (specific). And who's to say that all developers want to build this on ReactJS at all? There's a lot of VueJS proponents out there, who would've built the rest of their site in that stack, and aren't keen to also maintain a React app.

I've built a pseudo-code example to illustrate my points. Haven't tried to run it, but it shouldn't be too far off either :) https://github.com/chillu/react-hoc-customisation-example

**Comment by chillu** [comment]
Addressing a few specific points:

> The developer who finds value in a React implementation is probably the same developer who will be happy making their own React mini-app

Dunno, some devs will just want a fastest path to a useful baseline, tweak the colours, and leave it there. Which is a major goal of the CKAN integration as far as I understand. And we can achieve that through React just as much as SSViewer.

> It's possible that our React code will conflict with the sites own React code - what happens when some React 16 code runs on the same page as some React 10 code (for example)?

I think this stuff is sufficiently encapsulated now (even jQuery can run multiple instances unless you rely on globals, which no webpack build would). 

> Potentially sets a new trend? SilverStripe supported modules providing React code for front-end sites?

I'd frame our React implementation as a suggestion in a README, rather than a part of our API surface. Certain components could form part of the public API (e.g. prop signatures in `withCkan()` in my example), but we'd strongly lean on devs to e.g. just use Griddle and depend on their API guarantees.

**Comment by robbieaverill** [comment]
>I'm strongly in favour of making this a use case of a decoupled architecture, where not every data exchange needs to be funnelled through a monolithic stack like the CMS.

We can do that, and at the moment it is decoupled in so much as the actual data is coming from a CKAN API endpoint rather than from SilverStripe. For that reason, I think that rules out using the SilverStripe GraphQL server to power this too.

>My recommendation would be that you document how to customise the style of the output for developers.

Yeah this is probably going to be most of the use cases to be honest. However we present the data, we'll of course provide sufficient BEM classes attached to each element to allow for theming.

---

What I'm hearing is that we should ship a frontend React implementation by default, and clearly label it as an example of how to implement the API on the frontend.

We really just need to get the customised CKAN configuration out of the SilverStripe backend, which could be provided with a custom REST API endpoint much like the JSON form schema is for React forms in the CMS.

@chillu @scopeynz @nightjar @unclecheese if we're all in agreement with this, can we close this and create new tickets to implement this in React for the frontend (see @chillu's example repo above)?
