### ISSUE TITLE
Front end Text filter

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#74]
After #73 is done, create a filter type for a text filter.

Designs: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c09c9d18e1f85001158544f

**Comment by robbieaverill** [comment]
@sachajudd in the designs we have an example placeholder which is "Search a topic or organisation" - since this is dynamic, I'm wondering how we can easily make this localisable. I think we can either:

* make it "Search topics or organisations" to avoid the case where you have "a topic" versus "an organisation"
* make three possible scenarios:
  * "Search topics"
  * "Search topics or organisations" (uses `or` as the conjunctive)
  * "Search addresses, topics or organisations" (has a comma delimiter)
* not make them localisable at all, which would require devs to either build their own custom language strings in a custom frontend app and/or request a specific locale from the CKAN API. [This is possible](https://docs.ckan.org/en/ckan-2.7.3/contributing/i18n.html) via the API, but we haven't made any provisions for it in the CMS interface yet

Thoughts?

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/121, minimal consideration for localisation at this stage. This also adds a separate JS bundle for the frontend. I haven't used added any CSS yet, and have been testing the component via the silverstripe/admin story book and unit tests.

**Comment by sachajudd** [comment]
Hey @robbieaverill I really appreciate your thought process around how we could of solved this. After discussing with @clarkepaul we've decided that at this point we don't see the search field being dynamic and that the placeholder text can be removed due to accessibility contrast standards. I've updated the designs to clarify what we envisioned for the front-end, sorry for the misinformed designs.

**Comment by robbieaverill** [comment]
Great, thanks
