### ISSUE TITLE
SPIKE: Investigate React Router for the detail view

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#79]
CKAN pages (on the frontend) will have dynamic URL segments, e.g. `/my-ckan-page` or `/categories/browse/schools` for example. Those parts of the URL are defined by SilverStripe in the backend, and after that we'd like to use React router to handle showing a detail view for a particular CKAN record. For example:

* `/categories/browse/schools`: Rendered by SilverStripe, CKAN React app shows a list of schools
* `/categories/browser/schools/:school`: Rendered by SilverStripe, React router detects `:school` in route and shows the detail for that school

This spike is to investigate how this can be implemented with React router in combination with dynamic SilverStripe URL segments.

**Comment by robbieaverill** [comment]
Investigation so far - implementing the react-router-dom package onto a single page that is not part of a SPA (single page app [controlled by React]) is proving to be quite tricky.

We can get the relative URL (from the root) and pass it to the React app as a prop, so it knows which prefixes to give to each link/route matcher, and linking to subpages e.g. `/my-ckan-page/12345` where 12345 is an example ID of a record you've clicked on, however when you refresh the page from that URL the SilverStripe router takes priority and returns a 404, looking for 12345 as a child page of `my-ckan-page`. This is using the `BrowserRouter` component.

I looked into using `HashRouter` instead, which adds URL paramters in the form of `#/:recordID` for example, instead of adding slash components to the URL which get swallowed up by the SilverStripe router. This doesn't work at all, because when it initialises [the `HashRouter` finds the `base` tag and uses that as its base URL](https://github.com/ReactTraining/history/issues/94). What you end up with is that when you load the CKAN page you immediately get redirected to `/#/` (base tag is `/` and `#/` is the root react-router path).

Some solutions on the internet suggest providing a custom [history](https://github.com/ReactTraining/history) object to provide a custom `basename` property, rather than letting it assume it should be the value of the `base` tag, however `HashRouter` doesn't accept a `history` prop so this doesn't work.

This begs the question - how do we support child pages of a CKAN registry page, while still ensuring that a CKAN registry's internal sub-pages work (such as the detail view)?

I thought about two options:

* A query string router, where routes would look like `/my-ckan-page?item=12345`. This sounds OK in theory, but [react-router no longer supports query string routing](https://github.com/ReactTraining/react-router/issues/4410). I'm currently trying out [the qhistory package](https://www.npmjs.com/package/qhistory) which has an example of a `QueryRouter` for react-router v4, but it's not matching the sub-page route and rendering that page correctly at the moment, although I could easily have done something wrong.
* Add a SilverStripe middleware that analyses the request URL and tries to identify parts of the URL that should be treated as React-only route arguments, and ignores them from being included in the SilverStripe routing. This might work (in theory at least), but it would probably have some negative performance impact since it would potentially need to load the page for every route and check its type, as well as check that it doesn't have any child pages that _should_ be included in the routing that match the current URL. The last part of that sentence could be removed by us making a rule that "a CKAN Registry Page can not have any children, because it will interfere with frontend routing within the results view"

I'll update this with anything else I find, but there's a few things to think about already.

**Comment by robbieaverill** [comment]
Ok I've had success with disabling child pages of a CKAN registry pages and designating all sub-URL handling to the react-router. Will push a PR for review shortly.

**Comment by robbieaverill** [comment]
PR at #136 for consideration/review
