### ISSUE TITLE
Columns should be clickable, remove more options

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#84]
Noticing the columns have a more options button including "Edit" and "Delete". There shouldn't be the option to delete a column so this should be removed leaving the column to be clicked anywhere and taken to the columns settings.

![image](https://user-images.githubusercontent.com/24258161/50810400-567eed80-136e-11e9-8f58-b1eaf3b2e6f8.png)

- [x] Log new issue for re-enabling click to edit on inline editable rows (symbiote/silverstripe-gridfieldextensions): https://github.com/symbiote/silverstripe-gridfieldextensions/issues/279
- [x] [Remove delete action](https://github.com/silverstripe/silverstripe-ckan-registry/pull/88)

**Comment by robbieaverill** [comment]
This is the expected behaviour when using GridFieldEditableColumns from symbiote/silverstripe-gridfieldextensions, I believe it's there to remove ambiguity when you can click on either the row, the drag handle or the editable fields (checkboxes in this case). It also matches existing UX patterns in the CMS such as userforms, where you can't click on the row to edit it.

I think if we want to change this it should be raised on https://github.com/symbiote/silverstripe-gridfieldextensions and changed everywhere. How does that sound?

**Comment by ScopeyNZ** [comment]
Delete action PR is merged. @sachajudd Do you want to make a follow up issue on GridFieldExtensions? Seems like valid reasons that rows aren't clickable...

**Comment by sachajudd** [comment]
Yes please @ScopeyNZ that'd be great 🙂

**Comment by robbieaverill** [comment]
I've raised a separate issue to discuss the click handling change in gridfieldextensions: https://github.com/symbiote/silverstripe-gridfieldextensions/issues/279
