### ISSUE TITLE
Missing alert when "Resource name" is missing 

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#87]
As per designs we have an alert warning when a "Resource name" is missing.

[Style guide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bdbb4a2c4a8ff0011b1cf9a)

**Comment by robbieaverill** [comment]
It looks like at the moment there's no "Select..." empty option in the Resource name dropdown, so there'd be no way to get to this validation state. How did you reproduce this?

We can add an empty option in order to add the validation error, but at the moment it seems OK to me. Scenarios:

* Incorrect Data source URL entered: validation error on that field, Resource name is an empty, readonly text field
* Correct Data source URL entered: Resource name is a dropdown with available options, the first option is pre-selected by default

**Comment by sachajudd** [comment]
Okay yeah I'm happy to leave this one as is and close this issue.
